RSS_SOURCES = [
    {"name": "NYTimes Fashion & Style", "url": "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml", "category": "general"},
    {"name": "The Guardian Fashion", "url": "https://www.theguardian.com/fashion/rss", "category": "general"},
    {"name": "The Cut", "url": "https://www.thecut.com/rss/all.xml", "category": "general"},
    {"name": "WWD Fashion News", "url": "https://wwd.com/category/fashion-news/feed/", "category": "industry"},
    {"name": "Business of Fashion", "url": "https://www.businessoffashion.com/rss", "category": "industry"},
    {"name": "Fashionista", "url": "https://fashionista.com/.rss/full/", "category": "general"},
    {"name": "The Fashion Law", "url": "https://www.thefashionlaw.com/feed/", "category": "industry"},
    {"name": "Highsnobiety", "url": "https://www.highsnobiety.com/rss", "category": "streetwear"},
    {"name": "Hypebeast", "url": "https://hypebeast.com/feed", "category": "streetwear"},
    {"name": "Hypebae", "url": "https://hypebae.com/feed", "category": "streetwear"},
    {"name": "Harper's Bazaar", "url": "https://www.harpersbazaar.com/rss/all.xml", "category": "general"},
    {"name": "ELLE", "url": "https://www.elle.com/rss/all.xml", "category": "general"},
    {"name": "GQ", "url": "https://www.gq.com/feed/rss", "category": "men"},
    {"name": "Esquire", "url": "https://www.esquire.com/rss/all.xml", "category": "men"},
    {"name": "Dazed", "url": "https://www.dazeddigital.com/rss", "category": "culture"},
    {"name": "LVMH Newsroom", "url": "https://www.lvmh.com/news-documents/news/feed/", "category": "corporate"},
    {"name": "Kering Press", "url": "https://www.kering.com/en/press-releases/feed/", "category": "corporate"},
    {"name": "Nike News", "url": "https://news.nike.com/rss", "category": "brand"},
    {"name": "Adidas News", "url": "https://www.adidas-group.com/en/media/newsroom/rss/", "category": "brand"},
]