name: tests

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  root-tests:
    name: Root tests (crawler)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies (root)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (root)
        run: pytest -q tests

  backend-tests:
    name: Backend tests (API)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies (backend)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (backend)
        run: pytest -q